### PR TITLE
equality

### PR DESCRIPTION
**Pull request by PH7N**

### CODE REVIEW

**Comment by Ahwxorg** [comment]
@prplwtf

**Comment by PH7N** [comment]
> no because I am betterer

no u

**Comment by Ahwxorg** [comment]
In all seriousness, it's done - I believe - because I've been a bigger contributor to the project than others (mostly in support not on Git).

**Comment by prplwtf** [comment]
@Ahwxorg is part of the orginazation, which is why their name is bolded in the README. Changes like these could be put into issues or just questions directly to me instead of spam pull requests.

**Pull request closed without merging**
